---
title: "Project_PSTAT126"
author: "Xihao Wu & Anhui Shi"
date: "9/10/2018"
output:
  word_document: default
  html_document: default
---

```{r fig.align='center'}
#Load the data set, delete the data that we don't want
library(readr)
auto_mpg <- read_table2("auto-mpg.txt", col_names = FALSE)
auto_mpg<-auto_mpg[,-c(9,10,11)]
names(auto_mpg)<-c('mpg','cylinders','displacement','horsepower','weight','acceleration','modelyear','origin')
auto_mpg$horsepower <- as.numeric(auto_mpg$horsepower)
auto_mpg<-na.omit(auto_mpg)
auto_mpg$origin<-as.factor(auto_mpg$origin)
pairs(auto_mpg)


```



```{r fig.align='center'}
library(faraway)

mod.1 = lm(mpg ~ 1, data = auto_mpg[,-8])
mod.1.upper = lm(mpg ~ ., data = auto_mpg[,-8])

step(mod.1, scope = list(lower = mod.1, upper = mod.1.upper))
```


```{r fig.align='center'}
#Variable selection
library(leaps)
mod.2 = regsubsets(auto_mpg[,-c(1,8)], auto_mpg$mpg)
summary(mod.2)$which
summary(mod.2)$adjr2
summary(mod.2)$cp
```

```{r fig.align='center'}
#Residual Analysis
mod.2.selected = lm(mpg ~ weight  + modelyear + origin , data = auto_mpg)
yhat.2.selected= fitted(mod.2.selected)
e.2.selected = auto_mpg$mpg - yhat.2.selected
plot(yhat.2.selected, e.2.selected, xlab = 'Fitted value', ylab = 'Residual', main = 'Residual vs Fitted')
abline(h = 0, lty = 2)

#QQ-plot
qqnorm(e.2.selected)
qqline(e.2.selected)

#Shapiro-Wilk Test
shapiro.test(e.2.selected)

#boxcox
library(MASS)
boxcox(mod.2.selected)

boxcox(mod.2.selected, lambda = seq(-0.5,0, length = 10))
boxcox(mod.2.selected, lambda = seq(-0.3,-0.25, length = 10))

```

```{r fig.align='center'}
#Residual Analysis
mod.2.trans = lm(mpg^(-0.285) ~ weight  + modelyear + origin , data = auto_mpg)
yhat.2.trans= fitted(mod.2.trans)
e.2.trans = (auto_mpg$mpg)^(-0.285) - yhat.2.trans
plot(yhat.2.trans, e.2.trans, xlab = 'Fitted value', ylab = 'Residual', main = 'Residual vs Fitted')
abline(h = 0, lty = 2)

#QQ-plot
qqnorm(e.2.trans)
qqline(e.2.trans)

#Shapiro-Wilk Test
shapiro.test(e.2.trans)

summary(mod.2.trans)
```




```{r fig.align='center'}
#leverage
sort(hatvalues(mod.2.trans), decreasing = TRUE)[c(1,2,3,4,5)]

#studentized deleted residuals
sort(abs(rstudent(mod.2.trans)), decreasing = TRUE )[c(1,2,3,4,5)]

#Cook's distance
sort(cooks.distance(mod.2.trans), decreasing =TRUE)[c(1,2,3)]
```



```{r fig.align='center'}
#delete outlier 
mod.deleted= lm(mpg^(-0.285) ~ weight  + modelyear + origin , data = auto_mpg[-c(165,124,111), ] )
yhat.deleted= fitted(mod.deleted)
e.deleted = (auto_mpg[-c(165,124,111), ]$mpg)^(-0.285) - yhat.deleted

#QQ-plot
qqnorm(e.deleted)
qqline(e.deleted)

#Shapiro-Wilk Test
shapiro.test(e.deleted)


```

```{r fig.align='center'}
#Find interaction
mod.3.reduced  = lm(mpg^(-0.285) ~ weight  + modelyear + origin , data = auto_mpg)
mod.3.full =lm(mpg^(-0.285) ~ weight  + modelyear + origin + weight*modelyear + weight*origin + modelyear*origin , data = auto_mpg)
anova(mod.3.reduced, mod.3.full)

summary(mod.3.full)
```



```{r fig.align='center'}
#Final model
mod.final = lm(mpg^(-0.285) ~ weight  + modelyear + origin , data = auto_mpg )
summary(mod.final)
```
```{r fig.align='center'}


#Confidence Interval

new_ave = data.frame(weight = mean(auto_mpg$weight), modelyear = max(auto_mpg$modelyear), origin = as.factor(1) )

ci_ave = predict(mod.final , newdata = new_ave, interval = 'confidence', level = 0.95)
ci_ave^(-1/0.285)
```
```{r fig.align='center', echo=FALSE}

```

```{r fig.align='center', echo=FALSE}

```

```{r fig.align='center', echo=FALSE}

```
